# Generated by Django 5.2.17 on 2026-08-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
