# Generated by Django 5.2.17 on 2026-08-24 04:29

import django.db.models.deletion
import sewa.models.agreement_template
import sewa.models.property
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0002_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('sign_image', models.ImageField(upload_to=sewa.models.agreement_template.get_unique_file_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('sub_district', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=5)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('type', models.CharField(choices=[('HOUSE', 'House'), ('ROOM', 'Room')], default='HOUSE', max_length=5)),
                ('furnishing_type', models.CharField(choices=[('HOUSE', 'House'), ('ROOM', 'Room')], default='HOUSE', max_length=5)),
                ('land_area', models.IntegerField()),
                ('building_area', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
                ('total_bathrooms', models.IntegerField()),
                ('rental_cost_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('rental_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deposit_required', models.BooleanField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('UN_AVAILABLE', 'Unavailable')], default='DRAFT', max_length=12)),
                ('agreement_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa.agreementtemplate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sewa.property')),
            ],
        ),
    ]
