# Generated by Django 5.2.17 on 2026-08-24 04:33

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.management import create_permissions

def create_group_and_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    model_list = [
        'agreementtemplate',
        'propertyimage',
        'property',
    ]

    content_type_list = ContentType.objects.filter(model__in=model_list).all()

    landlord, landlord_created = Group.objects.get_or_create(name='landlord')

    for content_type in content_type_list:
        permissions = Permission.objects.filter(content_type__app_label=content_type.app_label,
                                                content_type__model=content_type.model)
        for permission in permissions:
            landlord.permissions.add(permission)

class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0003_agreementtemplate_property_propertyimage'),
    ]

    operations = [
        migrations.RunPython(create_group_and_permissions, lambda x, y: None)
    ]
