# Generated by Django 5.2.17 on 2026-08-25 03:11

import sewa.models.upload_image_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0004_create_group_permission_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sewa.models.upload_image_model.get_image_file_path)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing_type',
            field=models.CharField(choices=[('FULLY', 'Fully Furnished'), ('SEMI', 'Semi Furnished'), ('NO', 'Unfurnished')], default='HOUSE', max_length=5),
        ),
    ]
