# Generated by Django 5.2.17 on 2026-08-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0005_uploadimagemodel_alter_property_furnishing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
