# Generated by Django 5.2.17 on 2026-08-30 05:07

import django.db.models.deletion
import sewa.models.application
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0006_property_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('duration', models.IntegerField()),
                ('monthly_lease_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_file', models.FileField(upload_to=sewa.models.application.get_unique_file_path)),
                ('id_file', models.FileField(upload_to=sewa.models.application.get_unique_file_path)),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('ACC', 'Accepted'), ('REJ', 'Rejected'), ('PAI', 'Paid')], default='REQ', max_length=3)),
                ('reject_reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa.property')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('duration', models.IntegerField()),
                ('monthly_lease_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CUR', 'Current'), ('MOV', 'Moving In'), ('PRI', 'Prior')], default='CUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa.application')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa.property')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
