# Generated by Django 5.2.17 on 2026-09-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0007_application_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
