# Generated by Django 5.2.17 on 2026-09-12 23:55

import os
from django.db import migrations
from django.db import connection

def province_data_seed(apps, schema_editor):
    province_file_path = os.path.join(os.path.dirname(__file__), '../data/province.sql')

    with connection.cursor() as cursor:
        with open(province_file_path, 'r', encoding='utf-8') as f:
            for line in f:
                sql_statement = line.strip()
                schema_editor.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0009_province_regency'),
    ]

    operations = [
        migrations.RunPython(province_data_seed),
    ]
