# Generated by Django 5.2.17 on 2026-09-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0011_regency_data_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sub_district',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sewa.regency'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sewa.province'),
        ),
    ]
